version: '3.9'
  services:
    node:
      build: .
      environment:
        PORT: 3000
        DATABASE_HOST: mysql
        DATABASE_PORT: 3306
        DATABASE_USERNAME: "user"
        DATABASE_PASSWORD: "password"
        DATABASE_NAME: "databse"
      depends_on:
        - mysql
      ports:
        - 3000:3000
    mysql:
      image: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=my-secret
        - MYSQL_DATABASE=ynov
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pwd
      volume:
        - mysql-data:/var/lib/mysql
      ports:
        3306:3306
