version: '3.9'
  services:
    node:
      build: .
    mysql:
      image: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=my-secret
        - MYSQL_DATABASE=ynov
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pwd
